### PR TITLE
Update content and condition of mentee dashboard approval-state message

### LINKED ISSUE #362: Update content and condition of mentee dashboard approval-state message
**Is your feature request related to a problem? Please describe.**
The text content for mentee dashboard approval-state message is outdated and the condition for rendering it can be improved.

**Describe the solution you'd like**
Update the text content of the message and update the condition to render as follows:
- If `program?.state == "ONGOING"` and `mentee.state == "APPROVED"`, then show the success message.
- If `program?.state == "ONGOING"` and `mentee.state != "APPROVED", show the rejected message.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose
The purpose of this PR is to fix #362

## Goals
The text content for mentee dashboard approval-state message is outdated and the condition for rendering it can be improved.

## Approach
Update the text content of the message and update the condition to render as follows:

If program?.state == "ONGOING" and mentee.state == "APPROVED", then show the success message.
If program?.state == "ONGOING" and `mentee.state != "APPROVED", show the rejected message.

## Screenshots
N/A

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
None

## Test environment
Java 8, macOS 12.3, Chrome latest.

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]
Good job! @Madhawa97

**Comment by anjula-sack** [comment]
@Madhawa97 The build is falling, can you check? Try running that script locally. https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Review by anjula-sack — APPROVED** [review]
Thank you! @Madhawa97

**Comment by Madhawa97** [comment]
My pleasure @anjula-sack

**Pull request merged**
