### PR TITLE
Optimize bundle.js using webpack plugins

### LINKED ISSUE #183: Bundle.js file consumes more time to load
**Is your feature request related to a problem?**
- Bundle.js file is large in size compared to the rest. This causes the application load time very high.

**Describe the solution you'd like**
- Use Webpack plugins to optimize the bundle.js

**Additional context**
Full detailed thread: https://sef.discourse.group/t/optimizing-scholarx-demo-application-runtime-bundle-js-analysis/283

### PR DESCRIPTION
**Pull request by Gimhan-minion**
## Purpose
- The purpose of this PR is to fix #183 

## Goals
- To reduce the file size of bundle.js file

## Approach
- Used [Webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to analyze the bundle.js
- Used [Webpack-ModuleConcatenationPlugin](https://webpack.js.org/plugins/module-concatenation-plugin/) to concatenate more files.
- Used [Webpack-ContextReplacementPlugin](https://webpack.js.org/plugins/context-replacement-plugin/) to concatenate moment.js plugin and etc.

## Screenshots
Screenshot from 2021-06-06 07-47-13

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## More details
https://sef.discourse.group/t/optimizing-scholarx-demo-application-runtime-bundle-js-analysis/283

### CODE REVIEW

**Comment by Gimhan-minion** [comment]
I switched it from the development branch to the master branch in order to optimize the up & running application. Any thoughts? @jayasanka-sack @anjula-sack

**Comment by anjula-sack** [comment]
> I switched it from the development branch to the master branch in order to optimize the up & running application. Any thoughts? @jayasanka-sack @anjula-sack

Let's merge it for the development branch otherwise, we have to send another PR for it. Since we are treating the master branch as the production. We shouldn't merge anything to it rather than the development branch.  If it is urgent we can release a minor version.

**Comment by Gimhan-minion** [comment]
> > I switched it from the development branch to the master branch in order to optimize the up & running application. Any thoughts? @jayasanka-sack @anjula-sack
> 
> Let's merge it for the development branch otherwise, we have to send another PR for it. Since we are treating the master branch as the production. We shouldn't merge anything to it rather than the development branch. If it is urgent we can release a minor version.

Sure @anjula-sack Changed it!

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
@Gimhan-minion 
You might wanna take a rebase pull from the development branch
There are 3 commits in the PR, including the release merge commits, after changing the branch

**Comment by Gimhan-minion** [comment]
> @Gimhan-minion
> You might wanna take a rebase pull from the development branch
> There are 3 commits in the PR, including the release merge commits, after changing the branch

Oh my bad! Fixed it too 😄

**Review by Gravewalker666 — APPROVED** [review]
Perfect, Thank you @Gimhan-minion

**Pull request merged**
