### PR TITLE
Prevent users from accessing pages in wrong states

### LINKED ISSUE #301: Prevent users from accessing pages in wrong states
**Describe the bug**
Mentor application pages should be only accessible to users/mentors during MENTOR APPLICATION period
Mentee application pages should be only accessible to users/mentees during MENTEE APPLICATION period

**To Reproduce**
1. Go to a page using the URL of that page, in any state
2. See error

**Expected behavior**
Mentor application pages should be only accessible to users/mentors during MENTOR APPLICATION period
Mentee application pages should be only accessible to users/mentees during MENTEE APPLICATION period
If someone accesses those pages during an inaccessible state, redirect to the homepage

**Screenshots**
N/A

**Additional context**
Check the other pages as well

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #301

## Goals

- Prevent users from accessing pages in the wrong states.

## Approach

- Mentors: (Approved & Not Approved) Had access to Mentor dashboard in 
          'MENTOR_SELECTION' states. (Fixed)
- Not logged in user: Had access to Mentee Application. (Fixed)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
- OS: macOS Monterey
- Browser: Safari 14.0.1
- IDE: IntelliJ IDEA

### CODE REVIEW

**Comment by Piumal1999** [comment]
> * Not logged in user: Had access to Mentee Application. (Fixed)

After doing this change, the apply button will not be shown to the non-logged in users. Am I right? 


> * Mentors: (Approved & Not Approved) Had access to Mentor dashboard in
>   'MENTOR_SELECTION'
>   'MENTEE_APPLICATION',
>   'ADMIN_MENTEE_FILTRATION'
>   states. (Fixed)

Previously when they access the dashboard, it showed some kind of message about the current program state. So do we need to hide those buttons? @anjula-sack 

I think we need to do something like in #305 for mentor application views and mentor dashboards.

**Comment by kumuditha-udayanga** [comment]
> > * Not logged in user: Had access to Mentee Application. (Fixed)
> 
> After doing this change, the apply button will not be shown to the non-logged in users. Am I right?
> 
> > * Mentors: (Approved & Not Approved) Had access to Mentor dashboard in
> >   'MENTOR_SELECTION'
> >   'MENTEE_APPLICATION',
> >   'ADMIN_MENTEE_FILTRATION'
> >   states. (Fixed)
> 
> Previously when they access the dashboard, it showed some kind of message about the current program state. So do we need to hide those buttons? @anjula-sack
> 
> I think we need to do something like in #305 for mentor application views and mentor dashboards.

Yes, shall I display the button to non-logged-in users and redirect them instead of hiding the button.

**Comment by Piumal1999** [comment]
> shall I display the button to non-logged-in users and redirect them instead of hiding the button.

Yeah

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 currently in the "MENTOR-SELECTION" state, users who applied to be a mentor gets the "Manage" button, should we hide it?

**Comment by Piumal1999** [comment]
> in the "MENTOR-SELECTION" state, users who applied to be a mentor gets the "Manage" button, should we hide it?

What will be shown to them if they click the manage button during the mentor selection period?

**Review by anjula-sack — APPROVED** [review]
Thank you! @kumuditha-udayanga

**Pull request merged**
