### PR TITLE
Fix bugs related to mentor Application

### LINKED ISSUE #73: Bugs related to Mentor Application
**Is your feature request related to a problem?.**
- After Applying as a mentor, it should redirect to the homepage.
- Rename the button as "Apply as mentor" instead of "Apply as a mentor"

**Describe the solution you'd like**
- Edit the code to complete the above tasks.

**Additional context**
https://docs.google.com/document/d/1YiX0hik7V5DGB7f88HfkVT5Fk455kZ0LjYlJzqR-Z2I/edit?usp=sharing

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #73 

## Goals

- To change ```"Apply as a mentor"``` to ```"Apply as mentor"```
- Once the application is submitted redirect to home page

## Approach

- Edit the relevant code lines in ```/MentorApplication/index.tsx```

## Screenshots

Screenshot 2021-02-07 at 12 33 07

Screenshot 2021-02-07 at 12 33 16

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
MacOS Big Sur, Google Chrome

### CODE REVIEW

**Review by Gimhan-minion — DISMISSED** [review]
Thank you @kumuditha-udayanga 💯🤗

**Review by Gravewalker666 — DISMISSED** [review]
Nice 🙃, Thanks @kumuditha-udayanga

**Comment by Gravewalker666** [comment]
There's a linting error in the code dude, @kumuditha-udayanga can you check it again?
image

**Comment by Gimhan-minion** [comment]
@Gravewalker666 After submitting the mentor application the button still shows as `Apply as Mentor`. and when you click on that it redirects to a new application instead of the edit view. Should we fix that bug in the same PR or create another separate issue for that. WDYT?

**Review by Gimhan-minion — APPROVED** [review]

**Comment by Gravewalker666** [comment]
@Gimhan-minion I think it's better to do that in different PR. Let's merge this one and create another issue for that.

**Pull request merged**
