### PR TITLE
Add character limits to mentor/mentee applications

### LINKED ISSUE #312: Add character limits to mentor/mentee applications
**Is your feature request related to a problem? Please describe.**
In the mentee/mentor applications, we haven't validated the character count from the frontend. We need to prevent users from entering text exceeding the maximum character limit

**Describe the solution you'd like**
Every field in the mentee/mentor application should have a character limit. (Ex: for expertise, the character limit is 255)
Check the backend or the DB to find the character limits

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by miniskynet**
## Purpose

The purpose of this PR is to fix #312 

## Goals

Added a maxLength attribute to the input fields, which limits the user input character amount. The character count is also shown in the input field. 

## Screenshots

Mentor application:

Mentor

Mentee application :

Mentee

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by miniskynet** [comment]
@Piumal1999 @anjula-sack please check if this is okay

**Review by anjula-sack — APPROVED** [review]
Good job! @miniskynet

**Review by Piumal1999 — COMMENTED** [review]
Looks good to me. Well done @miniskynet 

@anjula-sack Are these maxLength values ok? Or maybe we can ignore the capacities in the DB columns and just keep shorter maxLength values relevant to the fields

**Comment by miniskynet** [comment]
thank you @Piumal1999 @anjula-sack

**Pull request merged**
