### PR TITLE
Move all the interfaces to a single file

### LINKED ISSUE #182: Reorganise the typescript interfaces
**Is your feature request related to a problem? Please describe.**
- Please follow this thread to understand the problem
https://sef.discourse.group/t/reorganising-typescript-interfaces-in-scholarx-app/291

**Describe the solution you'd like**
- Reorganise the typescript interfaces

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #182 

## Goals

- Maintaining a single type file to store the interfaces 

## Approach

- Created the `types.ts` file 
- Moved all the interfaces to the types file except prop types

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — DISMISSED** [review]
Looks good 
Nice job @anjula-sack, did you test this out?

**Comment by anjula-sack** [comment]
> Looks good
> Nice job @anjula-sack, did you test this out?

yeah I did but I'm gonna do it again after that I'll let you know

**Comment by Gravewalker666** [comment]
> > Looks good
> > Nice job @anjula-sack, did you test this out?
> 
> yeah I did but I'm gonna do it again after that I'll let you know

Cool

**Comment by anjula-sack** [comment]
> > > Looks good
> > > Nice job @anjula-sack, did you test this out?
> > 
> > 
> > yeah I did but I'm gonna do it again after that I'll let you know
> 
> Cool

Ready to be merged

**Review by Gravewalker666 — APPROVED** [review]
Amazing!! Now the code is so clean
Thanks, @anjula-sack

**Pull request merged**
