### PR TITLE
Fixed footer alignment in low resolution screens

### LINKED ISSUE #355: The footer is not aligned to the bottom
**Describe the bug**
- In some views, the footer is not aligned to the bottom of the screen.

**To Reproduce**
1. Go to a view with a footer
2. Scroll down to the footer
3. See error

**Expected behavior**
- Footer needs to be aligned to the bottom

**Screenshots**
Screenshot 2022-07-30 at 8 03 16 PM

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #355 
## Goals

Footer needs to be aligned to the bottom of the screens

## Approach

changed the min-height to 700px so the transition is not visible

## Screenshots

image

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
macOS 12.5
Chrome

### CODE REVIEW

**Comment by Madhawa97** [comment]
My bad. This doesn't fix the issue in all screens. Will push an update.

**Comment by anjula-sack** [comment]
> My bad. This doesn't fix the issue in all screens. Will push an update.

no worries, I'll make this draft

**Comment by Madhawa97** [comment]
It seems okay now. don't we have a PR preview in this repo?

**Comment by anjula-sack** [comment]
> It seems okay now. don't we have a PR preview in this repo?

we don't

**Comment by anjula-sack** [comment]
can you make this ready for review? @Madhawa97

**Comment by Madhawa97** [comment]
sure @anjula-sack

**Review by anjula-sack — APPROVED** [review]
Thank you! @Madhawa97

**Pull request merged**
