### PR TITLE
Fix crashing of MenteeApplication due to missing conditional rendering

### LINKED ISSUE #211: Mentee application is not accessible for mentees
**Describe the bug**
- During the mentee application period mentees should be able to apply as mentee. but now when someone tries to access it, it crashes.

**To Reproduce**
1. Go to a program where you can apply as a mentee
2. Click on a mentor
3. See error

**Expected behavior**
- Fix the mentor null issue

**Desktop (please complete the following information):**
 - OS: BigSur
 - Browser Chrome

### PR DESCRIPTION
**Pull request by NethmiRodrigo**
## Purpose
The purpose of this PR is to fix #211 

## Goals

Will only render mentor details if mentor object is not null

## Approach

Added conditional rendering to stop the component from trying to render mentor details before it is fetched.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Windows 10
Firefox

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]
Thank you for fixing this! @NethmiRodrigo

**Review by Gravewalker666 — COMMENTED** [review]
@anjula-sack do we have an issue created for this??

**Comment by anjula-sack** [comment]
> @anjula-sack do we have an issue created for this??

yes, I asked her to mention it.

**Comment by NethmiRodrigo** [comment]
> 
> 
> Thank you for fixing this! @NethmiRodrigo

Thanks for all the help :)

Mentioned the issue. Hope everything is good now

**Comment by Gravewalker666** [comment]
Nice work @NethmiRodrigo 
@anjula-sack can we release a bug fix version with this PR and check if it works on the deployed instance??

**Comment by anjula-sack** [comment]
> Nice work @NethmiRodrigo
> @anjula-sack can we release a bug fix version with this PR and check if it works on the deployed instance??

yeah I'll do a release.

**Pull request merged**
