### PR TITLE
Integrate manage mentees admin table with the backend

### LINKED ISSUE #277: Integrate the Admin-Manage Mentees table with the API
**Is your feature request related to a problem? Please describe.**
When the program is in the ADMIN_MENTEE_FILTRATION or WILDCARD state, admins should be able to manage the mentee states and assignedMentors using the manage mentees view. The design is already there, so we need to add the relevant endpoints and complete the UI. 

**Describe the solution you'd like**
Add the relevant endpoints and complete the UI.

Requirements:
- Only editable during `ADMIN_MENTEE_FILTRATION` and `WILDCARD` state
- Admins should be able to change mentee states
  - These states should be disabled but visible: APPROVED, REJECTED, ASSIGNED
  - Admin can manually change state to only these states: PENDING, POOL, DISCARDED, FAILED_FROM_WILDCARD
    - FAILED_FROM_WILDCARD should be enabled only on WILDCARD state
    - DISCARDED should be enabled only on ADMIN_MENTEE_FILTRATION state
  - Related endpoint:
    - `PUT /api/admin/mentees/{menteeId}/state` 
      RequestBody: `{ "state": EnrolmentState }`
      Returns `Mentee`

- Admins should be able to change assignedMentor
  - Admin can set any mentor as the assigned mentor
  - The menteeState automatically changes from the backend
  - Related endpoint:
    - `PUT /api/admin/mentees/{menteeId}/assign` 
      RequestBody: `{ "mentorId": mentorId }`
      Returns `Mentee`

**Describe alternatives you've considered**
N/A

**Additional context**
Design: https://github.com/sef-global/scholarx-frontend/pull/255

### PR DESCRIPTION
**Pull request by Gravewalker666**
## Purpose

The purpose of this PR is to fix #277 

## Goals

- To make the above table function

## Approach

- Used the ant design drawer and table to render the mentee application list and a single mentee 
- Used onSelect events to trigger the change of assigned mentor and the state 

## Screenshots

https://user-images.githubusercontent.com/45477334/147578012-87840347-90ce-464f-b00e-45c1b6aa5070.mov

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gravewalker666** [comment]
@Piumal1999 I made a separate component in the root components dir, so that we can use the same design everywhere for mentor profiles 
image

Shall we get this one merged and use this on mentee application particular mentor view as well(Your open PR)?

**Comment by Piumal1999** [comment]
> Shall we get this one merged and use this on mentee application particular mentor view as well(Your open PR)?

Yeah, that's good. I'll update that PR

**Review by Piumal1999 — APPROVED** [review]

**Comment by Piumal1999** [comment]
@Gravewalker666 According to our implementation, does the admin have to change mentee state to POOL, before assigning a mentor?

**Comment by Gravewalker666** [comment]
> @Gravewalker666 According to our implementation, does the admin have to change mentee state to POOL, before assigning a mentor?

Im not quite sure about how practical this implementation is, even I have my doubts :/

**Pull request merged**
