### PR TITLE
Remove "Prerequisites" from the mentee application

### LINKED ISSUE #169: Remove  "Prerequisites" from the mentee application
**Describe the bug**
 As "Prerequisites"  are unwanted in the mentee application. It should be removed.

**Expected behavior**
Remove "Prerequisites" from the mentee application

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose
The purpose of this PR is to fix  #169

## Goals
To remove "Prerequisites" from the mentee application.

## Approach
Removed "Prerequisites" from the mentee application

## Screenshots
Screenshot from 2021-06-06 10-31-03

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Great Job @gajindubandara well done.
Can we add some space between the profile picture and LinkedIn button?

**Comment by gajindubandara** [comment]
> Great Job @gajindubandara well done.
> Can we add some space between the profile picture and LinkedIn button?

Yeah sure! I'll do it

**Review by Gimhan-minion — DISMISSED** [review]
Good Job @gajindubandara. Can you attach a screenshot of the latest push?

**Comment by gajindubandara** [comment]
> Good Job @gajindubandara. Can you attach a screenshot of the latest push?

Screenshot from 2021-06-07 20-43-14

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Good job! @gajindubandara Can you update the `mentor` interface as well?

**Comment by gajindubandara** [comment]
> Good job! @gajindubandara Can you update the `mentor` interface as well?
Ok I'll do it

**Review by anjula-sack — DISMISSED** [review]
Thank you! @gajindubandara

**Review by Gimhan-minion — DISMISSED** [review]
Thank you @gajindubandara

**Review by Gravewalker666 — DISMISSED** [review]
Awesome, thank you @gajindubandara

**Comment by Gravewalker666** [comment]
@gajindubandara one last thing before merging
Can you please take a rebase pull from the development branch and only make it have one commit

**Review by Gimhan-minion — APPROVED** [review]

**Pull request merged**
